missing pagination on offer dashboard views
during development of large ecommerce site we ran into an exception
when accessing the list of offers and ranges:

AttributeError 'NoneType' object has no attribute 'paginator'
django_rangepaginator/templatetags/rangepaginator.py in paginate at line 12

This PR fixes all cases I could find where this happens, but chances are
some views need the same fix.